name: Generate Snake

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository's code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the snake animation and store it in the `dist/` folder
      - name: Generate Snake
        uses: Platane/snk@v2.0.1
        with:
          github_user_name: joaorunkel
          outputs: dist/snake.svg

      # Upload the generated snake.svg to the "output" branch
      - name: Push Snake to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
